spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/springadminsystem
    username: root
    password: mysqlroot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    cn:
      godbol: debug
#security:
#  basic:
#    enabled: true
storage:
  uploadPath=file:./upload